<?php
/**
 * Template part for displaying the CE User Agreement
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
 *
 * @package Bootscore
 * @version 6.0.0
 */

?>

<!-- User Agreement -->
<div class="user-agreement">
    <ol>
        <li>
            <h3>Introduction</h3>
            <p>THESE TERMS OF USE ("TERMS") BIND YOU, THE COMPANY YOU REPRESENT, AND ANY COMPANY THAT REGISTERED YOU (COLLECTIVELY "YOU") TO THE TERMS AND CONDITIONS SET FORTH HEREIN IN CONNECTION WITH YOUR USE OF COMICS EXPERIENCE, LLC.'S ("OUR", "WE", "US", OR "COMICS EXPERIENCE") INCLUDING, BUT NOT LIMITED TO, SOFTWARE, WEBSITE ACCESS, MOBILE APPLICATIONS, PRIME MEMBERSHIPS, MENTORING SERVICES, PROJECT MANAGEMENT OR CONSULTING OR CONNECTED APPLICATIONS SUCH AS APPLE TV, SERVICES OR OTHER OFFERINGS ON OUR WEBSITE OR BY US (COLLECTIVELY, OUR "SERVICES") OFFERED BY COMICS EXPERIENCE OR THROUGH ANY “THIRD PARTY PLATFORMS” (a<strong> third-party</strong> platform is a reusable software component developed to be either freely distributed or sold by an entity other than the original vendor of the development <strong>platform</strong>.) BY REGISTERING AND/OR USING ANY OF THE COMICS EXPERIENCE SERVICES, YOU AGREE TO BECOME BOUND BY THE TERMS. IF YOU DO NOT AGREE TO ALL THESE TERMS DO NOT USE THE COMICS EXPERIENCE SERVICES. COMICS EXPERIENCE'S ACCEPTANCE IS EXPRESSLY CONDITIONED UPON YOUR ASSENT TO ALL THESE TERMS, TO THE EXCLUSION OF ALL OTHER TERMS. THESE TERMS ARE CONSIDERED AN OFFER BY COMICS EXPERIENCE, ACCEPTANCE IS EXPRESSLY LIMITED TO THESE TERMS.</p>
            <p>Pre-arbitration clause:</p>
            <p>IMPORTANT: BY AGREEING TO THESE TERMS YOU AGREE TO RESOLVE DISPUTES WITH COMICS EXPERIENCE THROUGH BINDING ARBITRATION (AND WITH VERY LIMITED EXCEPTIONS, NOT IN COURT), AND YOU WAIVE CERTAIN RIGHTS TO PARTICIPATE IN CLASS ACTIONS, AS DETAILED IN SECTION 16.</p>
            <p>Any version of these Terms of Use in a language other than English is provided for convenience and you understand and agree that the English language will control if there is any conflict.</p>
        </li>
        <li>
            <h3>General</h3>
            <p>Our Services enable students ("Students") to connect with independent contractor instructors (the "Instructors", collectively with Students, the "Users") who provide live and recorded instruction, tutoring, and learning services (the "Courses") via Our Services Agreement (link to this Document). The Services include, without limitation, facilitating and hosting Courses and supporting materials, interactive message boards and feedback from Instructors.</p>
            <p>From time to time, We may update these Terms to clarify our practices or to reflect new or different practices, such as when We add new features, and Comics Experience reserves the right in its sole discretion to modify and/or make changes to these Terms at any time. If We make any material change to these Terms, We will notify You using prominent means such as by email notice sent to the email address specified in Your Account or by posting a notice through Our Services. Modifications will become effective on the day they are posted unless stated otherwise.</p>
            <p>Your continued use of Our Services after changes become effective shall mean that You accept those changes. You should visit the Services regularly to ensure You are aware of the latest version of the Terms, as any revised Terms shall supersede all previous Terms.</p>
            <p>Comics Experience may modify the Services or discontinue their availability at any time.</p>
            <p>You are solely responsible for all service, telephony, data charges and/or other fees and costs associated with Your access to and use of the Services, as well as for obtaining and maintaining all telephone, computer hardware, and other equipment required for such access and use.</p>
            <p>If You elect to access or use Our Services that involve payment of a fee, then You agree to pay, and will be responsible for payment of, that fee and all taxes associated with such access or use. If You provide credit card information to pay for such fees then You hereby represent and warrant that You are authorized to supply such information and hereby authorize Comics Experience to charge Your credit card on a regular basis to pay the fees as they are due.</p>
            <p>If Your payment method fails or Your Account is past due, then We may collect fees owed using other collection mechanisms. This may include charging other payment methods on file with Us and/or retaining collection agencies and legal counsel. We may also block Your access to any Services pending resolution of any amounts due by You to Comics Experience.</p>
            <p>All of Your use, access and other activities relating to the Services must be in compliance with all applicable laws and regulations, including, without limitations, laws relating to copyright and other intellectual property use, and to privacy and personal identity. Further, access to Our Services from territories where their contents are illegal is prohibited. Those who choose to access or use the Services from locations outside of the United States do so at their own initiative and are responsible for compliance with all local rules including, without limitation, rules about the internet, data, e-mail, or privacy. You further agree to comply with all applicable laws regarding the transmission of technical data exported from the United States or the country in which You reside. If You use the Services or Third Party Platforms from countries outside of the United States You must agree to abide by all local rules regarding online conduct and acceptable content.</p>
        </li>
        <li>
            <h3>General Disclaimer</h3>
            <p>The Services are only a marketplace for Instructors and Students. We do not hire or employ Instructors nor are We responsible or liable for any interactions involved between the Instructors and the Students who purchase any of Our Services. We are not responsible for disputes, claims, losses, injuries, or damage of any kind that might arise out of or relate to conduct of or between Instructors and/or Students, including, but not limited to, any Student's reliance upon any information provided by an Instructor. ANY OUTSIDE AGREEMENTS BETWEEN INSTRUCTORS AND STUDENTS WILL BE CONSIDERED A BREACH OF THIS AGREEMENT.</p>
            <p>We do not guarantee in any manner the reliability, validity, accuracy or truthfulness of Submitted Content. You also understand that by using the Services, Comics Experience may expose You to Submitted Content that You consider offensive, indecent, or objectionable. Comics Experience has no responsibility to keep such content from You and no liability for Your access or use of any Submitted Content, to the extent permissible under applicable law.</p>
            <p>The Services may give You access to links to third party platforms ("Third Party Platforms"), either directly or through Courses or Instructors. Comics Experience does not endorse any of these Third Party Platforms and does not control them in any manner. Accordingly, Comics Experience does not assume any liability associated with Third Party Platforms. You need to take appropriate steps to determine whether accessing a Third Party Platform is appropriate, and to protect Your personal information and privacy on such Third Party Platform.</p>
        </li>
        <li>
            <h3>Conduct</h3>
            <p>You may only access the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to Your use of the Services. You agree not to use the Services or the Company Content (as defined below) to recruit, solicit, or contact in any form, Instructors or potential users for employment or contracting for a business not affiliated with Us without Our advance written permission, which may be withheld in Our sole discretion. You assume any and all risks from any meetings or contact between You and any Instructors or other Users of the Services.</p>
        </li>
        <li>
            <h3>Specific Obligations of Students</h3>
            <p>As a Student, You represent, warrant and covenant that:</p>
            <ol>
                <li>You have read, understood, and agree to be bound by the pricing information (see the Pricing section) before using the Services or registering for a Course.</li>
                <li>You are over the age of 18, or, if not, You will only use the Services with the involvement, supervision, and approval of a parent or legal guardian. Children under the age of 13 may not register for an Account or register or purchase Courses.</li>
                <li>You will not upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation (commercial or otherwise) through the Services.</li>
                <li>You will not post or provide any inappropriate, offensive, racist, hateful, sexist, pornographic, false, misleading, incorrect, infringing, defamatory or libelous content or information.</li>
                <li>You will not copy, modify, reverse engineer, reproduce, distribute, publicly display, publicly perform, communicate to the public, create derivative works from, deface, tarnish, mutilate, hack, interfere with, or otherwise use and exploit any Company Content, the Services or Courses or Submitted Content except as permitted by these Terms or the relevant Instructor as applicable.</li>
                <li>You will not frame or embed the Services to circumvent the Services.</li>
                <li>You will not impersonate another person or gain unauthorized access to another person's Account.</li>
                <li>You will not introduce any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Services or operation thereof; scrape, spider, use a robot or other automated means of any kind to access the Services.</li>
                <li>You will not disclose any personal information to an Instructor, and otherwise will assume responsibility for controlling how Your personal information is disclosed or used, including, without limitation, taking appropriate steps to protect such information.</li>
                <li>You will not solicit personal information from any Instructor or other Student.</li>
            </ol>
            <p>Students understand and agree that Instructors from whom Students may have purchased Course(s) may choose to terminate their Accounts with Comics Experience and become inactive. Comics Experience does not guarantee Instructor availability to Students and shall not be held liable for any issues relating to Instructor availability.</p>
        </li>
        <li>
            <h3>Registration</h3>
            <p>To use certain Services, You will need to register and obtain an account and password. When You register, the information You provide to Us during the registration process will help Us in offering content, customer service, network management and other services. You are solely responsible for maintaining the confidentiality of Your account, UserName, and password (collectively, Your "Account") and for all activities associated with or occurring under Your Account. You represent and warrant that Your Account information will be accurate at all times. You must notify Us (a) immediately of any unauthorized use of Your Account and any other breach of security, and (b) ensure that You exit from Your Account at the end of each use of the Services. To the extent permissible under applicable law, we cannot and will not be responsible for any loss or damage arising from Your failure to comply with the foregoing requirements or as a result of use of Your Account, either with or without Your knowledge, prior to Your notifying Us of unauthorized access to Your Account.</p>
            <p>You may not transfer Your Account to any other person and You may not use anyone else's Account at any time. In cases where You have authorized or registered another individual, including a minor, to use Your Account, You are fully responsible for (i) the online conduct of such Student; (ii) controlling that Student's access to and use of the Services; and (iii) the consequences of any misuse.</p>
        </li>
        <li>
            <h3>Content, Licenses & Permissions</h3>
            <p>All software, technology, designs, materials, information, communications, text, graphics, links, electronic art, animations, illustrations, artwork, audio clips, video clips, photos, images, reviews, ideas, and other data or copyrightable materials or content, including the selection and arrangements thereof is "Content." Where Comics Experience provides Content to You in connection with the Services, including, without limitation, the software, the products and the site, it is "Company Content". Content uploaded, transmitted or posted to the Services by a User is "Submitted Content". Content remains the proprietary property of the person or entity supplying it (or their affiliated and/or third party providers and suppliers) and is protected, without limitation, pursuant to U.S. and foreign copyright and other intellectual property laws. You hereby represent and warrant that You have all licenses, rights, consents, and permissions necessary to grant the rights set forth in these Terms to Comics Experience with respect to Your Submitted Content and that Comics Experience shall not need to obtain any licenses, rights, consents, or permissions from, or make any payments to, any third party for any use or exploitation of Your Submitted Content as authorized in these Terms or have any liability to You or any other party as a result of any use or exploitation of Your Submitted Content as authorized in these Terms.</p>
            <p>Comics Experience hereby grants You (as a User) a limited, non-exclusive, non-transferable license to access and use Submitted Content and Company Content, for which You have paid all required fees, solely for Your personal, non- commercial, educational purposes through the Services, in accordance with these Terms and any conditions or restrictions associated with particular Courses or Services. All other uses are expressly prohibited absent Our express written consent. You may not reproduce, redistribute, transmit, assign, sell, broadcast, rent, share, lend, modify, adapt, edit, create derivative works of, license, or otherwise transfer or use any Submitted Content or Company Content unless We give You explicit permission to do so. Submitted Content and Company Content is licensed, and not sold, to You. Instructors may not grant You license rights to Submitted Content You access or acquire through the Services and any such direct license shall be null and void and a violation of these Terms.</p>
            <p>Notwithstanding the foregoing, We reserve the right to revoke this license to access and use Submitted Content and Company Content granted to You as described above, as further detailed below.</p>
            <p>COMICS EXPERIENCE RESPECTS ALL COPYRIGHT, PRIVACY, DEFAMATION AND OTHER LAWS RELATING TO CONTENT AND INFORMATION AND WILL NOT TOLERATE VIOLATION OF SUCH LAWS. NOTWITHSTANDING THE FOREGOING, COMICS EXPERIENCE DOES NOT SCREEN THE SUBMITTED CONTENT AND ALL USE OF THE SUBMITTED CONTENT BY YOU IS AT YOUR OWN RISK AND COMICS EXPERIENCE SHALL HAVE NO LIABILITY FOR SUCH USE. IN PARTICULAR, NO REVIEW OR POSTING OR APPEARANCE OF THE SUBMITTED CONTENT ON THE SERVICES OR THROUGH THE SERVICES IS INTENDED TO ACT AS AN ENDORSEMENT OR REPRESENTATION THAT ANY SUBMITTED CONTENT IS FREE OF VIOLATION OF ANY COPYRIGHT, PRIVACY OR OTHER LAWS OR WILL SUIT A PARTICULAR PURPOSE OR BE ACCURATE OR USEFUL. If You believe that Submitted Content of Yours violates any law or regulation or is inaccurate or poses any risk whatsoever to a third party it is Your responsibility to take such steps You deem necessary to correct the situation. If You believe that Submitted Content of a third party or any Company Content violates any laws or regulations, including, without limitation, any copyright laws, You should report it to Comics Experience in accordance with the procedures that We maintain as follows.</p>
            <p><strong>Intellectual Property Policy</strong></p>
            <p><strong>Copyright</strong></p>
            <p><strong>Notice and Procedure for Making Claims of Copyright or Other Intellectual Property Infringements.</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">Comics Experience, LLC. respects the intellectual property of others and takes the protection of copyrights and all other intellectual property very seriously, and we ask our instructors, students and other users of our website and services (the “Site”) to do the same. Infringing activity will not be tolerated on or through the Site.</li>
                <li>Comics Experience’s intellectual property policy is to (a) remove material that Comics Experience believes in good faith, upon notice from an intellectual property owner or their agent, is infringing the intellectual property of a third party by being made available through the Site, and (b) remove any Submitted Content posted to the Site by "repeat infringers." Comics Experience considers a "repeat infringer" to be any User that has uploaded Submitted Content to the Site and for whom Comics Experience has received more than two takedown notices compliant with the provisions of 17 U.S.C. 512(c) with respect to such Submitted Content. Comics Experience has discretion, however, to terminate the account of any User after receipt of a single notification of claimed infringement or upon Comics Experience’s own determination.</li>
            </ul>
            <p><strong>Procedure for Reporting Claimed Infringement.</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">If you believe that any content made available on or through the Site has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a "Notification of Claimed Infringement" containing the following information to the Designated Agent identified below. Your communication must include substantially the following;</li>
                <li style="margin-bottom: 1em;">A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that has/have been allegedly infringed;</li>
                <li style="margin-bottom: 1em;">Identification of works or materials being infringed, or, if multiple works are covered by a single notification, a representative list of such works;</li>
                <li style="margin-bottom: 1em;">Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Comics Experience to locate the material;</li>
                <li style="margin-bottom: 1em;">Information reasonably sufficient to permit Comics Experience to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted;</li>
                <li style="margin-bottom: 1em;">A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
                <li style="margin-bottom: 1em;">A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
                <li>For expedited review of your complaint, please fill out the form here (form in English only).</li>
            </ul>
            <p><strong>Designated Agent Contact Information.</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">Comics Experience’s Designated Agent for notices of claimed infringement can be contacted at:</li>
                <li style="margin-bottom: 1em;">Via E-mail: <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a></li>
                <li>Via U.S. Mail: Comics Experience, LLC. 301 Washington St., Shelbyville, KY 40065
                    Attn: Copyright Department/Legal</li>
            </ul>
            <p><strong>Counter Notification.</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">If you receive a notification from Comics Experience that material made available by you on or through the Site has been the subject of a Notification of Claimed Infringement, then you will have the right to provide Comics Experience with what is called a "Counter Notification." To be effective, a Counter Notification must be in writing, provided to Company's Designated Agent through one of the methods identified above, and include substantially the following information:</li>
                <li style="margin-bottom: 1em;">A physical or electronic signature of the subscriber;</li>
                <li style="margin-bottom: 1em;">Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</li>
                <li style="margin-bottom: 1em;">A statement under penalty of perjury that the subscriber has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</li>
                <li style="margin-bottom: 1em;">The subscriber's name, address, and telephone number, and a statement that the subscriber consents to the jurisdiction of Federal District Court for the judicial district in which the address is located, or if the subscriber's address is outside of the United States, for any judicial district in which Company may be found, and that the subscriber will accept service of process from the person who provided notification above or an agent of such person.</li>
                <li>A party submitting a Counter Notification should consult a lawyer or see 17 U.S.C. 512 to confirm the party's obligations to provide a valid counter notification under the Copyright Act.</li>
            </ul>
            <p><strong>False Notifications of Claimed Infringement or Counter Notifications.</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">The Copyright Act provides that:</li>
                <li style="margin-bottom: 1em;">
                    [a]ny person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. 512)] (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, shall be liable for any damages, including costs and attorney's' fees, incurred by the alleged infringer, by any copyright owner or copyright owner's authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [Comics Experience] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it.</li>
                <li style="margin-bottom: 1em;">17 U.S.C. 512(f).</li>
                <li style="margin-bottom: 1em;">Comics Experience reserves the right to seek damages from any party that submits a notification of claimed infringement or counter notification in violation of the law.</li>
                <li>For the avoidance of doubt, only notices submitted under the Digital Millennium Copyright Act and the procedures set forth in this section should be sent to the Designated Agent at <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a> or to the postal address identified above. Any other comments, compliments, complaints or suggestions about Comics Experience, the operation of the Site or any other matter should be sent to <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a>.</li>
            </ul>
            <p><strong>Trademark</strong></p>
            <ul style="list-style: none;">
                <li style="margin-bottom: 1em;">Procedure for submitting a Trademark Infringement Notice</li>
                <li style="margin-bottom: 1em;">The fastest and easiest way to submit a claim of trademark infringement to us is to send a notice containing the following information to the Designated Agent identified below. Please note that a copy of your notice will be sent to the party who posted the content you are reporting. Your communication must include substantially the following:</li>
                <li style="margin-bottom: 1em;">Your complete contact information (full name, mailing address and phone number).</li>
                <li style="margin-bottom: 1em;">The specific word, symbol, etc. in which you claim trademark rights.</li>
                <li style="margin-bottom: 1em;">The basis for your claim of trademark rights (such as a national or community registration), including registration number, if applicable.</li>
                <li style="margin-bottom: 1em;">The country or jurisdiction in which you claim trademark rights.</li>
                <li style="margin-bottom: 1em;">The category of goods and/or services for which you assert rights.</li>
                <li style="margin-bottom: 1em;">Information reasonably sufficient to permit us to locate the material on Comics Experience that you believe violates your trademark rights. The easiest way to do this is by providing web addresses (URLs) leading directly to the allegedly infringing content.</li>
                <li style="margin-bottom: 1em;">A description of how you believe this content infringes your trademark.</li>
                <li style="margin-bottom: 1em;">If you are not the rights holder, an explanation of your relationship to the rights holder.</li>
                <li style="margin-bottom: 1em;">The following statement: &ldquo;I have a good faith belief that use of the trademark as described above, in the manner complained of, is not authorized by the trademark owner, its agent, or the law&rdquo;</li>
                <li style="margin-bottom: 1em;">The following statement: &ldquo;The information in this notice is accurate, and I declare, under penalty of perjury, that I am the owner or authorized to act on behalf of the owner of a trademark that is allegedly infringed.&rdquo;</li>
                <li style="margin-bottom: 1em;">Your electronic signature or physical signature.</li>
                <li style="margin-bottom: 1em;">Designated Agent Contact Information.</li>
                <li style="margin-bottom: 1em;">Comics Experience’s Designated Agent for trademark infringement notices can be contacted at:</li>
                <li style="margin-bottom: 1em;"><a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a> if done via email</li>
                <li style="margin-bottom: 1em;">Comics Experience, LLC. 301 Washington St., Shelbyville, KY 40065 </li>
                <li>Attn: Copyright Department if done via physical mail.</li>
            </ul>
            <p>All rights not expressly granted in these Terms are retained by the Content owners and these Terms do not grant any implied licenses.</p>
            <p>You may decide to send us unsolicited ideas, including ideas for new promotions, products, services, applications, technologies or processes or other ideas (collectively, "User Ideas"). You must not transmit any User Ideas to or through the Services or Third Party Platforms, or to Us through e-mail, that You consider to be confidential or proprietary. You agree that We shall not be required to treat any User Ideas as being confidential or proprietary. You are responsible and liable for any User Ideas You submit. </p>
            <p>You agree that by submitting User Ideas to Us, including any concepts, know-how or ideas, You hereby grant Us a perpetual, worldwide, non-exclusive, royalty- free, sub licenseable and transferable license to use, reproduce, distribute, sell, exploit, prepare derivative works of and display the User Ideas in connection with the Services, and for Comics Experience's (and its successors) business, including without limitation, for promoting and redistributing part or all of the User Ideas (and derivative works thereof) in any media formats and through any media channels whether now known or hereafter developed, without payment or accounting to You or others. We are under no obligation to evaluate, review, or use any User Idea.</p>
        </li>
        <li>
            <h3>Pricing, Payment & Taxes</h3>
            <ol>
                <li>
                    <h4>Pricing.</h4>
                    You agree to pay the fees for Services that You purchase as set forth by designated Services pricing at www.comicsexperience.com.
                </li>
                <li>
                    <h4>Payment.</h4>
                    All payments are made to Comics Experience, LLC.
                    European Union Users. By purchasing Courses (e.g. clicking or tapping the relevant purchase button), You are confirming that You want the Course immediately credited to Your Account and that by doing so You are hereby waiving any and all cancellation rights under applicable laws, including but not limited to the EU Consumer Rights Directive (2011/83/EU) and/or any national laws implementing it. Refunds to You shall be applicable only in accordance with our refund policy described in section 8(6).
                </li>
                <li>
                    <h4>Taxes.</h4>
                    European Union. In the event that the sale or delivery of a Course or any Submitted Content to any Student in the European Union is subject to any value added tax ("VAT"), under applicable law, Comics Experience will collect and remit the VAT to the competent tax authorities for sales of such Courses or Submitted Content to Students in the European Union. Comics Experience may at its own discretion increase the Sale Price where Comics Experience is of the view that VAT may be due and Comics Experience will have a liability to account for such. You will indemnify and hold Comics Experience harmless against any and all claims by any tax authority for any underpayment of VAT, and any penalties and/or interest thereon.
                    All Other Countries. For sales of any Courses or Submitted Content in countries other than the European Union, You are responsible for remitting the taxes to the appropriate taxing authority (which may be different to the tax authority in Your own location). Comics Experience is unable to provide You with tax advice and You should consult Your own tax advisor.
                </li>
                <li>
                    <h4>Rounding Off.</h4>
                    Comics Experience may, in its sole discretion, round up or round down the Sale Price to the nearest whole functional base unit in which the Sale Currency is denominated (e.g. to the nearest dollar, euro or other supported currency); for example, Comics Experience will round up an amount of $101.50 to $102.00, and $101.49 to $101.00.
                    Some currencies are denominated in large numbers. In those cases, Comics Experience may determine the functional base unit in which those currencies are denominated to be 10, 100 or 1,000 of the currency; the corresponding examples for such currencies would be for Comics Experience to round up an amount of 1,045 up to 1,050 and 1,044 down to 1,040, or 35,450 up to 35,500 and 35,449 down to 35,400, or 837,500 up to 838,000 and 837,499 down to 837,000.
                </li>
                <li>
                    <h4>Refunds.</h4>
                    Comics Experience does not offer refunds for the Creators Workshop, Master Seminars, Creative Services or Mentoring. Our refund policy for courses is listed on the individual course pages. If there is no refund policy on any other service or listed on an individual course page, then no refunds are offered. Comics Experience reserves the right, in its sole discretion to amend or make exceptions to this policy for extenuating circumstances, on a case by case basis. To request a refund, please contact Us via <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a>. Please note that if We believe that You are abusing Our refund policy in Our sole discretion, We reserve the right to suspend or terminate Your Account and refuse or restrict any and all current or future use of the Services, without any liability to You. Any and all refunds will be at the sole discretion of Comics Experience.
                </li>
            </ol>
        </li>
        <li>
            <h3>Trademarks</h3>
            <p>The trademarks, service marks, and logos (the "Trademarks") used and displayed through Our Services or in any Company Content are Our registered or unregistered Trademarks or of Our suppliers or third parties and are protected pursuant to U.S. and foreign trademark laws. All rights are reserved and You may not alter or obscure the Trademarks, or link to them without Our prior approval.</p>
        </li>
        <li>
            <h3>Warranty Disclaimer</h3>
            <p>THE SERVICES, COMPANY CONTENT, SUBMITTED CONTENT, COURSES, AND ANY OTHER MATERIALS MADE AVAILABLE ON OR THROUGH THE USE OF THE SERVICES ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, COMICS EXPERIENCE AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON- INFRINGEMENT, ACCURACY, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. COMICS EXPERIENCE AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS DO NOT WARRANT THAT YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICES, THE SUBMISSIONS, THE SERVER(S) ON WHICH THE SERVICES ARE HOSTED, OR ANY SERVICES AVAILABLE ON ANY THIRD PARTY PLATFORM ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. NO OPINION, ADVICE OR STATEMENT OF COMICS EXPERIENCE OR ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS, AGENTS, MEMBERS OR VISITORS, WHETHER MADE THROUGH THE USE OF THE SERVICES, OR ON THIRD PARTY PLATFORMS OR OTHERWISE, SHALL CREATE ANY WARRANTY. YOUR USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION ANY SERVICES PROVIDED ON ANY THIRD PARTY PLATFORM, ARE ENTIRELY AT YOUR OWN RISK.</p>
        </li>
        <li>
            <h3>Limitation of Liability</h3>
            <p>NEITHER COMICS EXPERIENCE NOR ANY OF OUR SUBSIDIARIES, AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS OR SPONSORS, NOR OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS OR OTHER REPRESENTATIVES, ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES (INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS, LOSS OF DATA OR LOST PROFITS), UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE SERVICES AND/OR MATERIALS, INCLUDING ANY MATERIALS AVAILABLE THROUGH ANY THIRD PARTY PLATFORM, SUBMISSIONS, ANY LINKED WEBSITES OR ANY CODE, PRODUCT OR SERVICE PURCHASED, ACCESSIBLE OR USABLE THROUGH THE SERVICES OR ANY THIRD PARTY PLATFORM. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SERVICES, MATERIALS, INCLUDING ANY PRODUCTS OR SERVICES AVAILABLE THROUGH ANY THIRD PARTY PLATFORM, SUBMISSIONS OR ANY LINKED WEBSITES IS TO STOP USING THE SERVICES, MATERIALS, SUBMISSIONS, PRODUCTS, OR LINKED WEBSITES, AS APPLICABLE. THE SOLE AND EXCLUSIVE MAXIMUM LIABILITY TO COMICS EXPERIENCE FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE, SHALL BE THE TOTAL AMOUNT PAID BY YOU TO COMICS EXPERIENCE IN THE PRECEDING TWELVE (12) MONTHS, IF ANY, TO ACCESS OR USE THE SERVICES. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. NO COMMUNICATION OF ANY KIND BETWEEN YOU AND COMICS EXPERIENCE OR A REPRESENTATIVE OF COMICS EXPERIENCE CONSTITUTES A WAIVER OF ANY LIMITATIONS OF LIABILITY HEREUNDER OR CREATE ANY ADDITIONAL WARRANTY NOT EXPRESSLY STATED IN THE TERMS. MULTIPLE CLAIMS WILL NOT INCREASE THE MONETARY DAMAGES LIMIT STATED HEREIN. YOU AGREE THAT THE DAMAGE EXCLUSIONS IN THESE TERMS OF USE SHALL APPLY EVEN IF ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
            <p><em>Inaccuracies.</em> A possibility exists that the Services provided on any Third Party Platform could include inaccuracies or errors, or information or materials that violate these Terms. Additionally, a possibility exists that unauthorized alterations could be made by third parties to the Services available on any Third Party Platform. Although Comics Experience attempts to ensure the integrity of the Services on Third Party Platforms, we make no guarantees as to the Services' completeness or correctness. In the event that a situation arises in which the Services' completeness or correctness is in question, please submit a request to <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a> (with the subject line "Inaccuracies in Services on Third Party Platform Name") with, if possible, a description of the Services to be checked and the location (URL) where such Services can be found on Our Services or Third Party Platform at issue, as well as information sufficient to enable Us to contact You. We will try to address Your concerns as soon as reasonably practicable. For copyright infringement claims, see the above Intellectual Property section.</p>
            <p><em>System Outages.</em> Comics Experience periodically schedules system downtime for the Services for maintenance and other purposes. Additionally, unplanned system outages may occur. You agree that Comics Experience has no responsibility and is not liable for: (a) the unavailability of the Services including those available on Third Party Platforms; (b) any loss of materials, data, transactions or any other information or materials caused by such system outages; (c) the resultant delay, mis-delivery, or non-delivery of data, transactions or any other information or materials caused by such system outages; or (d) any outages caused by any third parties, including without limitation, any companies or servers hosting the Services, any Internet service providers, any Third Party Platforms, or any Internet facilities and networks.</p>
        </li>
        <li>
            <h3>Indemnification</h3>
            <p>You hereby indemnify, defend and hold harmless Comics Experience, and its affiliates, officers, directors, agents, partners, employees, licensors, representatives and third party providers from and against all reasonably foreseeable losses, expenses, damages, costs, claims and demands, including reasonable attorneys' fees and related costs and expenses, due to or arising out of Your breach of any representation or warranty hereunder. We reserve the right, at Our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by You under these terms, and in such case, You agree to fully cooperate as reasonably required with such defense and in asserting any available defenses.</p>
            <p><em>Notice for California Users.</em> Under California Civil Code Section 1789.3, California websites users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 400 R Street, Suite 1080, Sacramento, California, 95814, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
            <p><em>Statute of Limitations.</em> Any claim or cause of action arising out of or related to use of the Services, the Terms, or any services or information available through Third Party Platforms, must be filed within 1 year after such claim or cause or action arose regardless of any statutes or law to the contrary. In the event any such claim or cause of action is not filed within such 1-year period, such claim or cause of action are forever barred.</p>
        </li>
        <li>
            <h3>Termination</h3>
            <p>Comics Experience reserves the right to terminate, suspend, modify, or delete, at Our sole discretion, any (a) Submitted Content, Company Content, Courses, or any Service; and (b) Your access to Our Services or Your Account, as follows:</p>
            <ol>
                <li>If You breach or violate any of these Terms or any of Our applicable policies, as posted on Our Services from time to time, Comics Experience may take action immediately without prior notice to You. If We take action pursuant to this section, We shall not have any liability to You for any Course(s) You may have purchased nor for any other use of Our Services associated with Your Account. For avoidance of any doubt, You understand and agree that You will not be compensated nor be eligible for any refund under any circumstances for any such access lost to Our Services, including without limitation to Course(s) You may have purchased;</li>
                <li>We may also take action for any reason or no reason, in which case We will provide prior notice to You. If We take action pursuant to this section We will refund You for any access lost to Course(s) that You may have purchased during the three (3) months period prior to such termination, all in accordance with and subject to the terms of Our refund policy set forth herein </li>
                <li>You may terminate Your use of the Services at any time, either by ceasing to access them, or by deleting Your Account. We have no obligation to retain any of Your Account or Submitted Content for any period of time beyond what may be required by applicable law. Upon termination, You must cease all use of the Services and Content. Any accrued rights to payment and all representations and warranties shall survive termination.</li>
            </ol>
        </li>
        <li>
            <h3>Electronic Notices</h3>
            <p>By using Our Services or communicating with Comics Experience, You agree that Comics Experience may communicate with You electronically regarding security, privacy, and administrative issues relating to Your use of the Services or these Terms. If Comics Experience learns of a security system's breach, Comics Experience may attempt to notify You electronically by posting a notice through the Services or sending an email to You. You may have a legal right to receive this notice in writing. To receive free written notice of a security breach (or to withdraw Your consent from receiving electronic notice), please write to Comics Experience at <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a>. Notice will be deemed given twenty-four hours after e-mail is sent, unless the sending party is notified that the e-mail address is invalid. Alternatively, Comics Experience may give You legal notice by mail to a postal address, if provided by You through Your use any of the Services. In such case, notice will be deemed given three days after the date of mailing.</p>
        </li>
        <li>
            <h3>Miscellaneous</h3>
            <p><em>Entire Agreement. </em>These Terms and any policies applicable to You posted on Our Services constitute the entire agreement between the parties with respect to the subject matter hereof, and supersede all previous written or oral agreements between the parties with respect to such subject matter.</p>
            <p><em>Severability.</em> If any provision of these Terms is found to be illegal, void or unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions of these Terms.</p>
            <p><em>Waiver.</em> A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of Comics Experience to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.</p>
            <p><em>Notice.</em> Any notice or other communication to be given hereunder will be in writing and given by facsimile, postpaid registered or certified mail return receipt requested, or electronic mail.</p>
            <p><em>No Agency.</em> Nothing in these Terms shall be construed as making either party the partner, joint venture, agent, legal representative, employer, contractor or employee of the other. Neither Comics Experience nor any other party to these Terms shall have, or hold itself out to any third party as having, any authority to make any statements, representations or commitments of any kind, or to take any action that shall be binding on the other except as provided for herein or authorized in writing by the party to be bound.</p>
            <p><em>Governing Laws.</em> These Terms and Your use of the Services shall be governed by the substantive laws of the State of California without reference to its choice or conflicts of law principles that would require the application of the laws of another jurisdiction, and shall be considered to have been made and accepted in the State of Kentucky.</p>
        </li>
        <li>
            <h3>Agreement to Arbitrate and Class Action Waiver</h3>
            <p>THIS SECTION ONLY APPLIES TO USERS IN THE US AND CANADA.</p>
            <p>Before bringing a formal legal case, please first try contacting our support team at <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a>. Most disputes can be resolved that way.</p>
            <p><em>We Both Agree to Arbitrate.</em> If we can't resolve our dispute amicably, You and Comics Experience agree to resolve any claims relating to these Terms, or any of Our other terms posted on Our Services from time to time, through final and binding arbitration. This applies to all kinds of claims under any legal theory.</p>
            <p>Either of Us can bring a claim in small claims court in Shelby County, Kentucky or some other place we both agree on, if it qualifies to be brought in that court.</p>
            <p>In addition, if You or Comics Experience brings a claim in court that should be arbitrated or any of Us refuses to arbitrate a claim that should be arbitrated, the other of Us can ask a court to force Us to go to arbitration to resolve the claim (i.e., compel arbitration). You or Comics Experience may also ask a court to halt a court proceeding while an arbitration proceeding is ongoing.</p>
            <p><em>No Class Actions.</em> We all agree that we can only bring a claim against each other on an individual basis. That means: (a) neither You nor Comics Experience can bring a claim as a plaintiff or class member in a class action, consolidated action or representative action; (b) an arbitrator cannot combine more than one person's claim into a single case, and cannot preside over any consolidated, class or representative arbitration proceeding (unless we both agree to change this); (c) an arbitrator's decision or award in one person's case can only impact the person who brought the claim, not other Users, and cannot be used to decide other disputes with other Users. If a court decides that this subsection on "No Class Actions" is not enforceable or valid, then the entire section 16 (Agreement to Arbitrate and Class Action Waiver) will be null and void, but, the rest of the Terms will still apply.</p>
            <p><em>The Arbitration Process.</em> Any disputes between You and Comics Experience relating to the Services that involve a claim of less than US$10,000 must be resolved exclusively through binding non-appearance- based arbitration. A party electing arbitration shall initiate proceedings by filing an arbitration demand with the American Arbitration Association (AAA). The arbitration proceedings shall be governed by the AAA Commercial Arbitration Rules, Consumer Due Process Protocol, and Supplementary Procedures for Resolution of Consumer-Related Disputes. In addition, You and Comics Experience agree that the following rules shall apply to the arbitration proceedings: (a) the arbitration shall be conducted, at the option of the party seeking relief, by telephone, online, or based solely on written submissions; (b) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (c) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Any disputes between You and Comics Experience relating to the Services that involve a claim of less than US$10,000 must be resolved in accordance with the AAA's rules about whether the arbitration hearing has to be in-person.</p>
            <p><em>Jurisdiction for Legal Disputes Not Subject to Arbitration.</em> If the Agreement to Arbitrate is determined to be invalid or unenforceable or for any disputes that do not qualify for arbitration, the dispute shall be subject to the exclusive jurisdiction of the Federal and State courts located in, or nearest to Shelby County, Kentucky. You hereby consent and submit to the personal and exclusive jurisdiction of such courts for the purposes of litigating any such action.</p>
            <p><em>Changes.</em> Notwithstanding the provisions of the modification-related provisions above, if Comics Experience changes this "Agreement to Arbitrate and Class Action Waiver" section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by providing Comics Experience written notice of such rejection by email from the email address associated with your Account to: <a href="mailto:info@comicsexperience.com">info@comicsexperience.com</a>, within 30 days of the date such change became effective, as indicated by the "last updated on" language above. In order to be effective, the notice must include your full name and clearly indicate your intent to reject changes to this "Agreement to Arbitrate and Class Action Waiver" section. By rejecting changes, you are agreeing that you will arbitrate any dispute between you and Comics Experience in accordance with the provisions of this "Agreement to Arbitrate and Class Action Waiver" section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</p>
        </li>
    </ol>
</div>